# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(802, 610)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 121))
        self.label.setStyleSheet("background-color: rgb(7, 156, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 120, 801, 491))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menubutton = QtWidgets.QPushButton(self.frame)
        self.menubutton.setGeometry(QtCore.QRect(720, 440, 41, 41))
        self.menubutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubutton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(7, 156, 255);\n"
"")
        self.menubutton.setCheckable(True)
        self.menubutton.setAutoExclusive(False)
        self.menubutton.setObjectName("menubutton")
        self.menu = QtWidgets.QWidget(self.frame)
        self.menu.setEnabled(True)
        self.menu.setGeometry(QtCore.QRect(690, 330, 101, 101))
        self.menu.setStyleSheet("QWidget#menu{\n"
"border-radius:15px;\n"
"background-color: rgb(226, 226, 226);\n"
"box-shadow: 10px 10px;\n"
"border: 1px dotted;\n"
"}")
        self.menu.setObjectName("menu")
        self.layoutWidget = QtWidgets.QWidget(self.menu)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 79, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.entrybutton = QtWidgets.QPushButton(self.layoutWidget)
        self.entrybutton.setCheckable(False)
        self.entrybutton.setAutoExclusive(True)
        self.entrybutton.setObjectName("entrybutton")
        self.verticalLayout.addWidget(self.entrybutton)
        self.categorybutton = QtWidgets.QPushButton(self.layoutWidget)
        self.categorybutton.setCheckable(False)
        self.categorybutton.setAutoExclusive(True)
        self.categorybutton.setObjectName("categorybutton")
        self.verticalLayout.addWidget(self.categorybutton)
        self.collectionbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.collectionbutton.setCheckable(False)
        self.collectionbutton.setAutoExclusive(True)
        self.collectionbutton.setObjectName("collectionbutton")
        self.verticalLayout.addWidget(self.collectionbutton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Entries"))
        self.label.setText(_translate("Dialog", "Entries"))
        self.menubutton.setText(_translate("Dialog", "+"))
        self.entrybutton.setText(_translate("Dialog", "new entry"))
        self.categorybutton.setText(_translate("Dialog", "new category"))
        self.collectionbutton.setText(_translate("Dialog", "new collection"))
